object Deps {
    const val kotlin = "1.3.72"
    const val coroutines = "1.3.8"
    const val androidKtx = "1.3.1"
    const val activityKtx = "1.1.0"
    const val fragmentKtx = "1.2.5"
    const val androidLifecycle = "2.2.0"
    const val viewModelKtx = "2.2.0"
    const val lifecycleHilt = "1.0.0-alpha02"
    const val retrofit = "2.9.0"
    const val dagger = "2.28.3"
    const val hilt = "2.28.3-alpha"
    const val okhttpLoggingInterceptor = "4.8.1"
    const val androidAppCompat = "1.2.0"
    const val rxJava = "3.0.5"
    const val rxRelay = "3.0.0"
    const val rxBinding = "4.0.0"
    const val rxAndroid = "3.0.0"
    const val junit = "4.13"
    const val junitAndroid = "1.1.2"
    const val espresso = "3.3.0"
    const val constraintLayout = "2.0.1"
    const val swipeRefreshLayout = "1.1.0"
    const val recyclerView = "1.1.0"
}
